CREATE TABLE IF NOT EXISTS `RentHouse` (
`id` int NOT NULL AUTO_INCREMENT,
'date'DATE DEFAULT NULL,
'title'VARCHAR(30) DEFAULT NULL,
'address' VARCHAR(30) DEFAULT NULL,
'distance'VARCHAR(30) DEFAULT NULL,
'price'VARCHAR(15) DEFAULT NULL,
PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
